-- 26_founder_knowledge_market.sql
-- Amber Homes — Founder Knowledge Base update (Saad Waqas): Market Philosophy, Wave Cycles,
-- Developer Intelligence, Community & Investment Map, Risk Language, Client-Safe Scripts.
--
-- SAFE / IDEMPOTENT / ADDITIVE.
--   * Chunked into focused entries so Ask Amber's keyword retrieval (mentors.js) can find the
--     right founder view (tags are weighted retrieval keywords; category "Founder's Knowledge"
--     gets the founder priority boost and the [Founder's Knowledge] label in the AI prompt).
--   * Does NOT touch existing knowledge: the only delete targets THIS batch's own prior insert,
--     matched by the unique source tag below. On first run it deletes nothing. Re-running simply
--     refreshes this batch (no duplicates), leaving seeds 17/19/21 and any admin-added entries intact.
--   * visibility 'all' => available to Agent / Manager / Admin / Master Admin AI. Client-safe vs
--     internal phrasing is enforced by the Ask Amber system prompt, not by hiding rows.

begin;

delete from public.ai_knowledge
 where source = 'Founder KB v2 (Market, Developer, Community)';

insert into public.ai_knowledge (title, category, content, tags, visibility, status, priority, source) values

-- ===== PART 1: MARKET PHILOSOPHY =====
($KB$Market Philosophy: how the Dubai market really moves$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: Dubai real estate moves in CYCLES, not a straight line. There are highs, slower periods, corrections, recovery and new growth waves. It behaves more like a stock market than a fixed-return asset: timing, sentiment, entry price, developer quality, payment plan and location all matter. Dubai is not one market - it varies by developer, project, community, product type, entry price, payment plan, handover, sentiment, future supply, rental and resale demand. Agent rule: never say everything in Dubai makes money. Correct thinking - Dubai can build strong wealth when the buyer enters the RIGHT project, at the RIGHT price, with the RIGHT developer, location, payment plan and holding strategy. If you cannot explain WHY a project makes sense, do not push it. Client-safe line: Dubai is a strong long-term market, but it is not automatic that every property profits; the key is the right property at the right entry price - developer quality, location, payment plan and resale demand are very important.$KB$,
$KB$market, cycle, cycles, returns, fixed return, entry price, timing, sentiment, op, original price, how is dubai market, market philosophy, stock market, wealth, fundamentals$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

($KB$Hype vs fundamentals: what agents and clients get wrong$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: many agents chase hype - a project trends, others push it, and they sell it without checking whether it is genuinely good. Hype is not strategy. Before recommending anything, check entry price, payment plan, developer quality, location, resale potential, rental demand, future supply, product scarcity, market cycle and the client's objective. Clients often start believing everything in Dubai makes money when the market is high - this is dangerous. Even in a strong market, only good projects, good developers, strong locations, fair entry prices and manageable payment plans usually perform. Some resale is selling below OP (original price), which proves not every property profits. Client-safe explanation: Dubai is strong, but project selection and entry price matter a lot. What agents must NOT say: everything in Dubai makes money; any project will go up; this will definitely sell on premium; you cannot lose money in Dubai; prices always rise. What to say instead: Dubai is strong but selection is important, entry price matters, not every project performs the same, we need to compare properly before recommending.$KB$,
$KB$hype, fundamentals, research, below op, resale, client expectations, overpriced, mistakes, what not to say, selection$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

($KB$Master developers and the land advantage$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: Dubai is heavily shaped by major government-linked master developers (Meraas, Nakheel, Dubai Holding, Emaar). They own or control much of the prime land, so their land cost can be far lower than private developers who buy land later at market price. This gives master developers an edge in pricing, infrastructure planning, destination creation, buyer confidence and resale trust. A private developer can still deliver a good project, but if it launches at a very high price without a real location or product advantage, the upside can be limited. Agent lesson: understand the difference between a master developer and a private developer before recommending. Client-safe line: developer selection is very important in Dubai - major master developers often have stronger land positions, better infrastructure planning and stronger long-term buyer confidence, which is why we compare developer quality before recommending any project.$KB$,
$KB$master developer, private developer, land, land cost, meraas, nakheel, dubai holding, emaar, government linked, pricing, infrastructure, destination$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Why Dubai: global destination, why people invest, resilience$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: after COVID, Dubai became a global RELOCATION city, not just an investment or holiday destination. Safety, lifestyle, zero personal income tax, business freedom, modern infrastructure, world-class schools and healthcare, and long-term residency (Golden Visa) drew entrepreneurs, families and high-net-worth individuals. Dubai combines the energy of a major financial city with luxury-destination lifestyle, while staying cleaner, safer and more business-friendly than many older cities such as London, New York, Singapore and Hong Kong. People invest for tax efficiency, strong rental demand, freehold ownership for foreigners, safety, global connectivity and a high-quality life - all in one place. Resilience: Dubai's government is fast; it identifies problems and acts quickly, often turning uncertainty into opportunity. Client-safe line: Dubai offers tax efficiency, safety, rental demand, infrastructure, connectivity and long-term residency - one of the few cities where you can invest, live, work, run a business and build long-term wealth in the same place.$KB$,
$KB$why dubai, why invest, covid, golden visa, tax, no income tax, london, new york, singapore, hong kong, relocation, resilience, government, freehold, safety, lifestyle$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Current market phase and outlook (founder view, not a guarantee)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view (current): a SELECTIVE buyer's market. After regional uncertainty some buyers paused and international capital slowed; summer naturally slows activity as people travel. Resale is under pressure in some segments - sellers who bought high on tough payment plans can struggle to exit at cost or premium, creating some below-OP opportunities. Buyers have more options and take more time, and they prefer flexible payment plans (e.g. 40/60, 30/70) that reduce pressure; developers can still succeed when they offer strong plans. Outlook is a founder VIEW, not a guarantee: from September/October onward the market may become more active if sentiment improves, summer ends, regional uncertainty reduces and international capital returns; over 6-12 months stronger activity is possible if confidence returns; over five years Dubai may enter a new chapter. Never present this as guaranteed future performance. Client-safe line: the market today is more selective - for serious buyers that can mean less pressure, more room to compare, and in some cases better value.$KB$,
$KB$current market, buyers market, buyer market, payment plan, 40/60, 30/70, outlook, forecast, summer, sentiment, september, october, slow, resale pressure, should i buy$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

-- ===== PART 2: WAVE CYCLES =====
($KB$Dubai market wave cycles and history$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: Dubai moves in WAVES; the investors who do best understand the cycle and buy on fundamentals, not hype. History: the first major freehold wave began in the mid-2000s (Law No. 7 of 2006) when Dubai opened ownership to foreigners - high excitement, light regulation, led by Emaar and Nakheel. The 2008 global financial crisis hit a highly leveraged, speculative market hard; the strongest, government-linked developers survived, proving not all developers are equal. Escrow regulation (Law No. 8 of 2007) made off-plan far safer - developers now need land rights, approvals, escrow and compliance before selling. The Expo 2020 announcement restored confidence; 2014-2015 were strong; post-2015 slowed (oil weakness, regional tensions, rising supply); 2019 to early 2020 were among the lowest points; then post-COVID demand transformed the market. Lesson: today's Dubai is far more regulated and mature than pre-2008. Do NOT say off-plan has no risk or that escrow makes delay impossible - say off-plan is more regulated today, but we still choose the right developer, project, payment plan and location.$KB$,
$KB$cycles, history, waves, 2008, financial crisis, escrow, law 7 2006, law 8 2007, freehold, regulation, expo 2020, supply, off plan risk, mature market$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Luxury property cycle: boom, more supply, what changed$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: luxury boomed after COVID because Dubai had a shortage of high-end inventory (from 2017 to 2020 launches skewed affordable and mid-market). When wealthy families relocated, large villas, penthouses and prime waterfront homes were scarce - that scarcity pushed prices up (Palm Jumeirah, Emirates Hills, Dubai Hills villas, large apartments). The earlier cycle rewarded 1 and 2 bedroom apartments and townhouses; after 2021-2022 larger units, big villas and penthouses made exceptional gains because of undersupply. Now developers have launched much more luxury supply, so selection is critical - not every luxury project will repeat early post-COVID gains. The next stronger opportunity may shift toward well-priced townhouses and smaller villas, because large villas have become unaffordable for many buyers. Client-safe line: luxury remains important, but the market has changed - more luxury supply means careful selection matters, and well-priced townhouses and smaller villas with strong family demand can be the better opportunity now.$KB$,
$KB$luxury, villas, penthouses, large apartments, palm jumeirah, emirates hills, dubai hills, scarcity, supply, undersupply, townhouses, small villas$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Townhouses, small villas and the end-user shift$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: townhouses and small villas can perform well now because many end-users want more space but cannot afford large villas at today's prices. A strong developer launching townhouses around AED 2.3M-3M with an attractive payment plan can see strong demand - families value space, community living, privacy and rental appeal. Payment plan is decisive for end-users (40/60, 30/70, lower construction-stage payment, larger handover payment). Caution: compare off-plan pricing with ready and resale options, which can sit at similar levels. The market is becoming more end-user driven - many buyers see Dubai as a 5-10 year home (family use, residence, schooling, Golden Visa, long-term wealth). Agent lesson: do not sell only quick flips - sell lifestyle, family demand, long-term value and practical payment plans. Client-safe line: a well-priced townhouse by a strong developer with a good payment plan can be attractive, but we still compare it with resale options.$KB$,
$KB$townhouse, small villa, end user, family, payment plan, 2.3m, 3m, flip, lifestyle, long term, space, community$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Objection: client says Dubai is a bubble$KB$, $KB$Founder's Knowledge$KB$,
$KB$Client concern: Dubai is a bubble. Founder view: it is not - a bubble is prices rising without fundamentals; Dubai has real fundamentals (people and businesses relocating, government improving infrastructure, visas and global positioning). But not every property is a good investment - some are overpriced and will underperform, so the strategy is the right developer, location, product and entry price, not buy anything. Safe reply (WhatsApp): I understand the concern, but Dubai is not one single market. Some projects can be overpriced, yet Dubai's fundamentals are strong - safety, tax efficiency, infrastructure, lifestyle, business opportunity and global demand. The key is not to buy randomly but to buy the right project at the right price. Call script: explain that a bubble means prices without fundamentals, acknowledge that some projects are overpriced and will underperform, then steer to selection (developer, location, product, entry price). Closing question: Are you looking for a safer long-term asset, or are you open to a higher-growth opportunity if the numbers make sense?$KB$,
$KB$bubble, objection, dubai bubble, overpriced, fundamentals, crash, risk, script, closing question$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Client-safe scripts: how is the market / should I buy now$KB$, $KB$Founder's Knowledge$KB$,
$KB$Client-safe script - How is the Dubai market right now? Dubai is still a strong long-term market, but right now it is more selective. Buyers are taking time, comparing options and looking for real value - which can be a good phase for serious buyers, with less pressure than peak hype. The key is not to buy randomly: developer, location, payment plan and entry price matter a lot. Dubai moves in cycles, and the investors who do well buy strong assets at the right time and the right price. Client-safe script - Should I buy now or wait? Waiting can make sense with a clear strategy, but waiting blindly can mean missing good opportunities. Right now the market is more selective, so there is more room to compare and negotiate. If we find a strong project by a good developer at a fair entry price with a practical payment plan, it can be worth considering. I would compare 2 or 3 strong options and only proceed if the numbers and location make sense.$KB$,
$KB$market script, how is the market, should i buy, buy now or wait, wait, client safe, whatsapp, value$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

-- ===== PART 3: DEVELOPER INTELLIGENCE =====
($KB$Developer classification and best buyer (overview)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder classification (best buyer in brackets). Emaar - the giant master developer, global brand, massive communities, strong resale and rental (most buyer profiles). Meraas - niche, design-led, lifestyle, often waterfront or prime urban (lifestyle and rental). Nakheel - iconic waterfront (Palm Jumeirah, Dubai Islands, Palm Jebel Ali). Dubai Holding - government-linked holding behind Meraas and Nakheel, now Emaar's largest shareholder. Wasl - government-linked, strong land, hospitality and mixed-use. Damac - largest private developer, strong sales machine, branded residences, flexible payment plans (not the first choice for pure investment unless price, location and product are strong). Sobha - quality and finishing, often priced high (good for end-users; check entry price). Ellington - design-led, end-user focused (study investment upside). Omniyat - benchmark ultra-luxury (wealthy lifestyle buyers). Beyond - Omniyat-group, more accessible, emerging locations (verify each project). Aldar - Abu Dhabi leader, Dubai JVs with Dubai Holding. Modon - Abu Dhabi government-linked master plans (e.g. Hudayriyat). H&H - boutique luxury, low-density (wealthy end-users if price is fair). Majid Al Futtaim - strong master developer (Tilal Al Ghaf, Ghaf Woods). Rule: a great developer at the wrong price can still be a weak investment.$KB$,
$KB$developers, developer comparison, classification, emaar, meraas, nakheel, dubai holding, wasl, damac, sobha, ellington, omniyat, beyond, aldar, modon, h&h, majid al futtaim, best buyer$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

($KB$Emaar intelligence: brand, communities, quality, payment, resale$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: Emaar is Dubai's number one master developer and one of the safest brands - it creates full communities, not just buildings (Burj Khalifa, Dubai Mall, Downtown, Marina, Emirates Living, Dubai Hills, Creek Harbour, The Valley, The Oasis, Emaar South, Rashid Yachts, Emaar Beachfront). Its biggest strength is brand, community planning, resale confidence, rental demand, and a product range from about AED 1M apartments to ultra-luxury villas - it serves almost every buyer. Best buyer: safe and long-term investors, Emaar loyalists, overseas buyers, families and end-users who value resale liquidity. If a client says only Emaar, do not argue - ask whether they want rental income, capital appreciation, family use or long-term holding, then match the community. Quality is solid and reliable (not always the most ultra-luxury finishing) - people buy the community experience. Payment plans are usually stricter, often around 80/20 - always verify the current plan. Resale: historically many Emaar buyers profited, but returns depend heavily on entry price; premium can take longer than Meraas, Nakheel or Dubai Holding (sometimes around three years as the community matures). Do NOT say Emaar is guaranteed profit or that it always sells on premium - say it is one of Dubai's strongest brands, but we still check entry price, payment plan, unit, view, handover and resale demand.$KB$,
$KB$emaar, downtown, dubai marina, dubai hills, dubai creek harbour, arabian ranches, emaar south, the valley, the oasis, rashid yachts, emaar beachfront, payment plan, 80/20, resale, premium, brand$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

($KB$Amber Homes developer strategy (INTERNAL - phrase safely for clients)$KB$, $KB$Founder's Knowledge$KB$,
$KB$INTERNAL guidance - do not say to a client verbatim; phrase it safely. Founder view: Amber Homes is not purely developer-centric - it is product- and opportunity-centric: right developer, product, location, price, payment plan and buyer profile. Historically Amber Homes sold a lot of Emaar; in recent years it has focused strongly on Meraas and Nakheel because of strong relationships, allocation strength and the quality of unique projects from these developers. Amber Homes has strong access and credibility with Meraas, Nakheel and Dubai Holding. Internal advantage: many agents in the market push other developers because they cannot get allocation in Meraas, Nakheel or top government-linked launches - Amber Homes should use its allocation strength as a competitive advantage when guiding clients to genuinely strong opportunities. Client-safe version to actually say: Amber Homes works closely with Dubai's leading developers and focuses on matching clients with the right project, not just any project - we compare developer, location, payment plan, resale demand and entry price before recommending.$KB$,
$KB$amber homes, strategy, allocation, competitive advantage, meraas, nakheel, dubai holding, internal, product centric, relationships$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

-- ===== PART 4: COMMUNITY AND INVESTMENT MAP =====
($KB$Community selection: how to evaluate any area$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder view: never recommend a community blindly. First understand whether it is mature, early-stage, end-user, rental-yield, capital-appreciation, luxury, waterfront, family-focused, overpriced, under- or over-supplied, or only worth it on a strong resale deal. Before recommending any area, check developer, entry price, price per square foot, payment plan, handover, current resale and rental demand, service charges, future supply, community maturity, connectivity, end-user appeal and the client's objective. Agent rule: do not sell the area - sell the logic. Every recommendation must have a reason. Investment status language to use: Buy / Hold / End-user / Avoid / Only if below OP / Only if resale deal.$KB$,
$KB$community, area, evaluate, investment status, entry price, price per sqft, supply, service charges, maturity, connectivity, how to choose area$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Waterfront communities map (Palm Jebel Ali, Dubai Islands, City seaside)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder waterfront map. Palm Jebel Ali (Nakheel) - a grand, newer, larger, more refined long-term waterfront plan (luxury, beach and coral villas); view it long-term, not as a flip; best for patient long-term, luxury, Golden Visa and lifestyle buyers. Frame it as a long-term waterfront scarcity play - do NOT say it will definitely become the next Palm Jumeirah. Dubai Islands (Nakheel) - closer to the city with more advanced infrastructure, so potentially shorter-term results than Palm Jebel Ali; Nakheel-led parts (townhouses, villas, mansions, residences) can be strong; study Bay Grove Residences, Rixos Residences, and Ellington and Beyond projects; good for buyers who missed Palm Jumeirah. Jumeirah Bay (Meraas) - super-prime trophy market now (Bvlgari); the big investment entry was earlier. Bluewaters (Meraas) - limited supply; major appreciation already happened, now lifestyle and scarcity. La Mer / Port de La Mer (Meraas) - now more end-user; J1 Beach adds lifestyle. Emaar Beachfront - strong earlier window; be selective now. Rashid Yachts and Marina (Emaar) - some attractive resale; mid-to-long-term waterfront. Dubai Creek Harbour (Emaar) - a mix of Downtown and Marina; mid-to-long-term, not a quick flip. Note: freehold supply on the seaside of Sheikh Zayed Road is limited - scarcity supports long-term demand when entry price is fair.$KB$,
$KB$waterfront, palm jebel ali, dubai islands, jumeirah bay, bluewaters, la mer, port de la mer, emaar beachfront, rashid yachts and marina, dubai creek harbour, nakheel, meraas, sheikh zayed road, seaside, scarcity, bay grove, rixos, ellington, beyond$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Central and lifestyle communities (Downtown, Business Bay, City Walk, D3, DIFC)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder central and lifestyle map. Downtown Dubai (mostly Emaar, mature) - iconic prestige and rental/lifestyle address; capital appreciation is now slower because it is mature; best for end-users, luxury living, prestige and long-term holding, not the fastest growth play. Business Bay - very mixed (ultra-luxury towers alongside average private-developer ones); BE CAREFUL - some private developers price towers high by saying next to Downtown, sometimes above good Downtown resale; never recommend blindly - check developer, price per square foot, exact location, view, service charges, building quality and resale comparables, and whether the price is justified. Dubai Marina - mature, strong rental and lifestyle, slower growth. City Walk (Meraas) - chic, low-rise, central, very strong for rentals due to limited supply and a unique lifestyle (can beat Downtown on rentals); strong mid-to-long-term, not short-term flipping; Central Park added a major residential phase; Crestlane at City Walk is a newer low and mid-rise concept toward Al Wasl Road with potential skyline and sea views. Dubai Design District / D3 (Meraas) - strong rental story: high office and professional demand, limited residential supply, central, with a waterfront component (study Design Quarter). DIFC - interesting mid-to-long-term: financial institutions, hedge funds and family offices create strong executive tenant demand.$KB$,
$KB$downtown, business bay, dubai marina, city walk, crestlane, central park, dubai design district, d3, difc, rental, lifestyle, meraas, emaar, central, office demand$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Family, villa and townhouse communities map$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder family map. Dubai Hills Estate (Emaar) - strong central family community (villas, townhouses, golf, mall, schools); good resale apartment deals can be attractive if the entry price is right. The Valley (Emaar) - family-focused; the best angle is resale (3-4 bedroom townhouses or larger-plot Farm Gardens villas) at a fair price. The Oasis (Emaar) - lagoon and luxury villas; look for early-phase resale at OP or below. Arabian Ranches 1 and 2 - mature, mainly end-user; AR3 may have limited near-handover opportunities only if priced well versus ready. Nad Al Sheba Gardens - villas and townhouses close to Downtown, DIFC, Meydan, MBR City and District One; attractive if you find a good deal - entry price is the key. Dubai South - long-term infrastructure play (Al Maktoum airport); townhouses and villas usually better than apartments. Expo City - interesting if the payment plan is strong (e.g. post-handover) - verify current plans. Tilal Al Ghaf (Majid Al Futtaim) - excellent when bought early (Elan, Harmony, Aura, Alaya, Serenity); now more end-user unless a strong resale deal appears. Jumeirah Park and Jumeirah Islands - mature family villa communities, good for end-use and long-term holding, not fast appreciation.$KB$,
$KB$dubai hills, the valley, the oasis, arabian ranches, nad al sheba gardens, meydan, mbr city, district one, dubai south, expo city, tilal al ghaf, jumeirah park, jumeirah islands, family, villa, townhouse, emaar, majid al futtaim, resale$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Mid-tier and caution areas (be price-disciplined)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder caution map - be price-disciplined. JVC and JVT - mid to lower tier, heavily supplied with private-developer apartments; work only if the entry price is very strong; risky for capital appreciation. Sobha Hartland - good quality but can be overpriced for investment; better for end-users; check entry price. Town Square - not high-end; prices have already moved a lot; be cautious and prefer better alternatives. Dubai Sports City and Motor City - mostly mature and end-user, not high-end; price-driven yield plays only. Al Furjan - mostly mature; good end-user and rental depending on project and price; investment must be project-specific. JLT - mature; strong rental in selected towers; slower growth. Dubai Silicon Oasis - mature and end-user; limited upside unless entry price is very strong. Damac Hills - mature, better for end-use. Damac Lagoons - only if a very good townhouse resale deal. Rule: never recommend Damac or any of these blindly - check price, phase, payment remaining, resale comparables, handover and demand.$KB$,
$KB$jvc, jvt, sobha hartland, town square, dubai sports city, motor city, al furjan, jlt, dubai silicon oasis, dso, damac hills, damac lagoons, caution, supply, yield, overpriced$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

($KB$Abu Dhabi investment map (Yas, Saadiyat, Hudayriyat)$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder Abu Dhabi map - more controlled and longer-term. Developers: Aldar (Abu Dhabi leader) and Modon (government-linked). Yas Island - the main area where many investors buy; strong lifestyle, entertainment, family and rental demand; well-priced townhouses or affordable apartments can be strong investments. Saadiyat Island - already appreciated significantly, now more luxury and end-user. Hudayriyat Island (Modon) - a beautiful new master plan, strong long-term opportunity, with attractive payment plans; study townhouses, villas and apartments. Al Reem Island and Al Raha Beach are also relevant. Frame Abu Dhabi as lifestyle plus limited supply plus government-backed master planning. Never say Abu Dhabi is better than Dubai, or Dubai is better than Abu Dhabi, in every case - it depends on the client and the deal.$KB$,
$KB$abu dhabi, yas island, saadiyat island, hudayriyat island, al reem, al raha beach, aldar, modon, payment plan, long term$KB$,
'all','active',2,'Founder KB v2 (Market, Developer, Community)'),

-- ===== RISK LANGUAGE (always-included compliance) =====
($KB$Do Not Say / Safe phrases (founder safety rules)$KB$, $KB$Compliance - Do Not Say (Founder)$KB$,
$KB$Never make fake promises and never guarantee: ROI, capital appreciation, rental yield, premium, allocation, discount, Golden Visa approval, resale before handover, developer delivery date, or future market direction. Agents must NOT say: Dubai always goes up; every property in Dubai makes money; this will definitely double; there is no risk; you cannot lose money in Dubai; prices will definitely increase from September; the bull run is guaranteed; this project will definitely sell on premium; Golden Visa is guaranteed; ROI is guaranteed; Emaar is guaranteed profit; Business Bay is always good because it is next to Downtown; Palm Jumeirah will still double from here; JVC is always good for investment; Palm Jebel Ali will definitely become the next Palm Jumeirah; Tilal Al Ghaf will keep doubling. Agents SHOULD say: Dubai moves in cycles; the right project can perform well; entry price is critical; developer quality matters; location and payment plan matter; not every property performs the same; we need to compare the project properly; this has potential, but we must evaluate the numbers; subject to availability and developer confirmation. Safe phrases: subject to availability; subject to developer confirmation; subject to authority approval; based on current market information; this is a founder market view, not a guarantee; we must verify the latest details before confirming; the entry price must be studied carefully. Protect Amber Homes credibility - never use founder knowledge to pressure a client dishonestly, never quote confidential internal strategy or allocation advantage to a client, and never say Saad guarantees.$KB$,
$KB$do not say, compliance, safe phrases, guarantee, roi, golden visa, premium, appreciation, never say, risk language, credibility$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)'),

($KB$Founder master instruction: think like an advisor, not a listing sender$KB$, $KB$Founder's Knowledge$KB$,
$KB$Founder master instruction: guide agents to think like investment advisors, not listing senders. Always evaluate developer, location, entry price, payment plan, product type, resale demand, rental demand, current market cycle, the client's objective and holding period. Core view: Dubai is one of the world's strongest markets, but it rewards intelligent buying, not blind buying. Emaar is the number one master developer and a strong long-term brand; Meraas, Nakheel, Dubai Holding, Emaar, Majid Al Futtaim, Omniyat, Beyond, H&H, Aldar and Modon can create strong opportunities when the entry price is right; evaluate private developers carefully. Mature communities are often better for end-use and rental stability than fast appreciation; early-stage waterfront, family communities, townhouses, villas and strong master-developer projects can offer better upside if bought correctly. Always ask the client's purpose first, give a reason for every recommendation, avoid guarantees, and move serious clients toward a call, meeting, site visit, shortlist, EOI or booking. Remind agents: you make money when you buy correctly, not only when you sell.$KB$,
$KB$master instruction, advisor, how to think, closing, purpose, eoi, booking, meeting, site visit, strategy, buy correctly$KB$,
'all','active',1,'Founder KB v2 (Market, Developer, Community)');

commit;

-- Verify after running:
--   select count(*) from public.ai_knowledge where source = 'Founder KB v2 (Market, Developer, Community)';   -- expect 21
--   select title, priority from public.ai_knowledge where source = 'Founder KB v2 (Market, Developer, Community)' order by priority, title;
